/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Factura } from './factura';
import { Boleto } from './boleto';


export interface BoletosFactura { 
    codBoletoFactura?: number;
    codBoleto?: number;
    codFactura?: number;
    usuarioIng?: string | null;
    fechaIng?: string;
    usuarioAct?: string | null;
    fechaAct?: string | null;
    codBoletoNavigation?: Boleto;
    codFacturaNavigation?: Factura;
}

