/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sala } from './sala';
import { Boleto } from './boleto';
import { Pelicula } from './pelicula';


export interface Funcione { 
    codFuncion?: number;
    codSala?: number;
    codPelicula?: number;
    estado?: string | null;
    fechaHoraInicio?: string;
    fechaHoraFin?: string;
    usuarioIng?: string | null;
    fechaIng?: string;
    usuarioAct?: string | null;
    fechaAct?: string | null;
    codSalaNavigation?: Sala;
    boletos?: Array<Boleto> | null;
    codPeliculaNavigator?: Pelicula | null;
}

