/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoImagen } from './tipoImagen';
import { Pelicula } from './pelicula';


export interface ImagenPelicula { 
    cod_imagen?: number;
    cod_pelicula?: number;
    imagen?: string | null;
    urlImagen?: string | null;
    imagenbase64?: string | null;
    nombreimagen?: string | null;
    tipo_imagen?: number;
    codTipoImagenNavigator?: TipoImagen;
    codPeliculaNavigation?: Pelicula;
}

