/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Factura } from './factura';


export interface Promociones { 
    id_promocion?: number;
    nombre?: string | null;
    descripcion?: string | null;
    estado?: string | null;
    fecha_ing?: string;
    usuario_ing?: string | null;
    fecha_act?: string | null;
    usuario_act?: string | null;
    facturas?: Array<Factura> | null;
}

