/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImagenPelicula } from './imagenPelicula';


export interface TipoImagen { 
    cod_tipo_imagen?: number;
    nombre?: string | null;
    fecha_ing?: string;
    usuario_ing?: string | null;
    imagenes?: Array<ImagenPelicula> | null;
}

